#!/usr/bin/env bash
set -eu -o pipefail
shopt -u expand_aliases
IFS=$'\n\t'

SOURCE_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
# shellcheck source=src/helpers/is-changed.bash
source "${SOURCE_DIR}/helpers/is-changed.bash"

if [[ ${GIT_GRAPNEL_AUTO_INSTALL:-0} -eq 0 ]]; then exit 0; fi

if [[ -f package-lock.json ]] && is_changed package-lock.json; then
	npm clean-install
	exit 0
fi

if [[ -f package.json ]] && is_changed package.json; then
	npm install
	exit 0
fi
