#!/usr/bin/env bash
set -eu -o pipefail
shopt -u expand_aliases
IFS=$'\n\t'

SOURCE_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
# shellcheck source=src/helpers/confirm.bash
source "${SOURCE_DIR}/helpers/confirm.bash"
# shellcheck source=src/helpers/is-own-repo.bash
source "${SOURCE_DIR}/helpers/is-own-repo.bash"

if is_own_repo || [[ ${GIT_GRAPNEL_LINT_ON_COMMIT:-0} -eq 0 ]]; then exit 0; fi

readarray -t staged_files <<< "$(git --no-pager diff --staged --diff-filter=d --name-only | rg '\.(js|cjs|mjs|ts|tsx|rs)$')" || true
if [[ ${#staged_files[@]} -eq 0 || "${staged_files[0]}" == '' ]]; then exit 0; fi

# Lint staged JavaScript & TypeScript files
if [[ -f package.json ]] && jq --exit-status '.devDependencies.eslint' package.json &>/dev/null; then
	npx eslint --fix --max-warnings 1 "${staged_files[@]}"
fi

# Lint all Rust files
if [[ -f Cargo.toml ]]; then
	cargo clippy --fix --no-deps
fi
